name: moneytama
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3

  cupertino_icons: ^1.0.8
  logging: ^1.2.0
  get_it: ^8.0.3
  path_provider: ^2.0.11
  provider: ^6.0.0
  flutter_svg: ^2.0.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: any

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.png"